export interface MarketplaceTranslator {
  id: string;
  name: string;
  name_uz?: string | null;
  name_ru?: string | null;
  name_en?: string | null;
  name_ar?: string | null;
  city: string;
  city_uz?: string | null;
  city_ru?: string | null;
  city_en?: string | null;
  city_ar?: string | null;
  hsk_level: number | null;
  self_declared_hsk?: number | null;
  buraq_verified_hsk?: number | null;
  buraq_verified_at?: string | null;
  specializations: string[] | null;
  bio?: string | null;
  bio_uz?: string | null;
  bio_ru?: string | null;
  bio_en?: string | null;
  bio_ar?: string | null;
  price_per_day: number | null;
  hourly_rate?: number | null;
  daily_rate?: number | null;
  is_verified: boolean;
  is_available: boolean;
  avatar_url: string | null;
  intro_video_url?: string | null;
  rating: number;
  total_reviews: number;
  total_bookings?: number;
  completed_bookings?: number;
  years_experience?: number;
  age?: number | null;
  gender?: string | null;
  telegram_username?: string | null;
  whatsapp_number?: string | null;
  user_id?: string | null;
  has_personal_car?: boolean | null;
  has_chinese_driving_license?: boolean | null;
  avg_reliability?: number | null;
  avg_expertise?: number | null;
  avg_punctuality?: number | null;
  avg_language?: number | null;
  [key: string]: unknown;
}
