-- Add translation columns to wholesale_markets
ALTER TABLE public.wholesale_markets 
ADD COLUMN IF NOT EXISTS name_uz TEXT,
ADD COLUMN IF NOT EXISTS name_ru TEXT,
ADD COLUMN IF NOT EXISTS name_en TEXT,
ADD COLUMN IF NOT EXISTS name_ar TEXT,
ADD COLUMN IF NOT EXISTS description_uz TEXT,
ADD COLUMN IF NOT EXISTS description_ru TEXT,
ADD COLUMN IF NOT EXISTS description_en TEXT,
ADD COLUMN IF NOT EXISTS description_ar TEXT,
ADD COLUMN IF NOT EXISTS city_uz TEXT,
ADD COLUMN IF NOT EXISTS city_ru TEXT,
ADD COLUMN IF NOT EXISTS city_en TEXT,
ADD COLUMN IF NOT EXISTS city_ar TEXT,
ADD COLUMN IF NOT EXISTS category_uz TEXT,
ADD COLUMN IF NOT EXISTS category_ru TEXT,
ADD COLUMN IF NOT EXISTS category_en TEXT,
ADD COLUMN IF NOT EXISTS category_ar TEXT;

-- Add translation columns to production_hubs
ALTER TABLE public.production_hubs 
ADD COLUMN IF NOT EXISTS industry_uz TEXT,
ADD COLUMN IF NOT EXISTS industry_ru TEXT,
ADD COLUMN IF NOT EXISTS industry_en TEXT,
ADD COLUMN IF NOT EXISTS industry_ar TEXT,
ADD COLUMN IF NOT EXISTS description_uz TEXT,
ADD COLUMN IF NOT EXISTS description_ru TEXT,
ADD COLUMN IF NOT EXISTS description_en TEXT,
ADD COLUMN IF NOT EXISTS description_ar TEXT,
ADD COLUMN IF NOT EXISTS city_uz TEXT,
ADD COLUMN IF NOT EXISTS city_ru TEXT,
ADD COLUMN IF NOT EXISTS city_en TEXT,
ADD COLUMN IF NOT EXISTS city_ar TEXT;

-- Add translation columns to companies
ALTER TABLE public.companies 
ADD COLUMN IF NOT EXISTS name_uz TEXT,
ADD COLUMN IF NOT EXISTS name_ru TEXT,
ADD COLUMN IF NOT EXISTS name_en TEXT,
ADD COLUMN IF NOT EXISTS name_ar TEXT,
ADD COLUMN IF NOT EXISTS description_uz TEXT,
ADD COLUMN IF NOT EXISTS description_ru TEXT,
ADD COLUMN IF NOT EXISTS description_en TEXT,
ADD COLUMN IF NOT EXISTS description_ar TEXT,
ADD COLUMN IF NOT EXISTS city_uz TEXT,
ADD COLUMN IF NOT EXISTS city_ru TEXT,
ADD COLUMN IF NOT EXISTS city_en TEXT,
ADD COLUMN IF NOT EXISTS city_ar TEXT,
ADD COLUMN IF NOT EXISTS industry_uz TEXT,
ADD COLUMN IF NOT EXISTS industry_ru TEXT,
ADD COLUMN IF NOT EXISTS industry_en TEXT,
ADD COLUMN IF NOT EXISTS industry_ar TEXT;

-- Add translation columns to exhibitions
ALTER TABLE public.exhibitions 
ADD COLUMN IF NOT EXISTS name_uz TEXT,
ADD COLUMN IF NOT EXISTS name_ru TEXT,
ADD COLUMN IF NOT EXISTS name_en TEXT,
ADD COLUMN IF NOT EXISTS name_ar TEXT,
ADD COLUMN IF NOT EXISTS description_uz TEXT,
ADD COLUMN IF NOT EXISTS description_ru TEXT,
ADD COLUMN IF NOT EXISTS description_en TEXT,
ADD COLUMN IF NOT EXISTS description_ar TEXT,
ADD COLUMN IF NOT EXISTS city_uz TEXT,
ADD COLUMN IF NOT EXISTS city_ru TEXT,
ADD COLUMN IF NOT EXISTS city_en TEXT,
ADD COLUMN IF NOT EXISTS city_ar TEXT,
ADD COLUMN IF NOT EXISTS venue_uz TEXT,
ADD COLUMN IF NOT EXISTS venue_ru TEXT,
ADD COLUMN IF NOT EXISTS venue_en TEXT,
ADD COLUMN IF NOT EXISTS venue_ar TEXT,
ADD COLUMN IF NOT EXISTS category_uz TEXT,
ADD COLUMN IF NOT EXISTS category_ru TEXT,
ADD COLUMN IF NOT EXISTS category_en TEXT,
ADD COLUMN IF NOT EXISTS category_ar TEXT;